/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    pages: Page;
    videos: Video;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {
    home: Home;
    navigation: Navigation;
    stats: Stat;
    'annual-report': AnnualReport;
    territories: Territory;
    contacts: Contact;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'annual-report': AnnualReportSelect<false> | AnnualReportSelect<true>;
    territories: TerritoriesSelect<false> | TerritoriesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
  };
  locale: 'uk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  hasEnglish?: boolean | null;
  title: string;
  publishedAt: string;
  /**
   * Напр.: «Житло для ВПО»
   */
  tag?: string | null;
  cover?: (number | null) | Media;
  /**
   * Показується в списку новин. 1–2 речення.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Заповнюється автоматично із заголовка.
   */
  slug?: string | null;
  /**
   * Для переадресації старих посилань.
   */
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Коротко: що зображено. Читається програмами екранного доступу.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Текстові сторінки сайту. Де яка сторінка в меню — дивіться на головній сторінці адмінки («Структура сайту»).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  hasEnglish?: boolean | null;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Частина адреси після домену. Не змінюйте без потреби — старі посилання перестануть працювати.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Сторінка «Відеоматеріали». Відео можна завантажити файлом або вставити посилання (MP4 чи YouTube).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  description?: string | null;
  source?: ('link' | 'file') | null;
  /**
   * Напр.: https://www.youtube.com/watch?v=… або пряме посилання на .mp4
   */
  url?: string | null;
  /**
   * MP4, бажано до 100 МБ.
   */
  file?: (number | null) | Media;
  /**
   * Якщо не вибрати — покажемо кадр із самого відео (для YouTube — його обкладинку).
   */
  poster?: (number | null) | Media;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  hasEnglish?: T;
  title?: T;
  publishedAt?: T;
  tag?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  slug?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  hasEnglish?: T;
  title?: T;
  content?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  source?: T;
  url?: T;
  file?: T;
  poster?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    kicker?: string | null;
    title?: string | null;
    text?: string | null;
    primary?: {
      label?: string | null;
      /**
       * Напр.: tel:1548 або /news
       */
      url?: string | null;
    };
    secondary?: {
      label?: string | null;
      /**
       * Напр.: tel:1548 або /news
       */
      url?: string | null;
    };
    flagMode?: ('animated' | 'video') | null;
    /**
     * Найкраще — 1920×1080 або 3840×2160 (4K), до 15 МБ, без звуку, із безшовним повтором.
     */
    flagVideo?: (number | null) | Media;
    /**
     * 1 — як у файлі. 0.5 — вдвічі повільніше.
     */
    videoSpeed?: number | null;
    /**
     * 0 — прапор нерухомий. 0.3 — повільно. 1 — швидко.
     */
    flagSpeed?: number | null;
  };
  statement?: {
    title?: string | null;
    text?: string | null;
  };
  /**
   * Порядок можна змінювати перетягуванням.
   */
  cards?:
    | {
        color?: ('navy' | 'yellow' | 'sky' | 'white') | null;
        size?: ('big' | 'wide' | 'normal') | null;
        live?: boolean | null;
        icon?:
          | (
              | 'building'
              | 'search'
              | 'phone'
              | 'heart'
              | 'warning'
              | 'scales'
              | 'home'
              | 'map'
              | 'document'
              | 'info'
              | 'globe'
            )
          | null;
        label?: string | null;
        /**
         * Напр.: 1548 або 1,4 млн
         */
        number?: string | null;
        title?: string | null;
        text?: string | null;
        chips?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        linkLabel?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  evacuation?: {
    show?: boolean | null;
    highlight?: string | null;
    title?: string | null;
    /**
     * Номери ставляться автоматично. Кожен новий рядок у тексті — окремий абзац.
     */
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    footer?: string | null;
    footerHighlight?: string | null;
  };
  resources?:
    | {
        label: string;
        url?: string | null;
        icon?:
          | (
              | 'building'
              | 'search'
              | 'phone'
              | 'heart'
              | 'warning'
              | 'scales'
              | 'home'
              | 'map'
              | 'document'
              | 'info'
              | 'globe'
            )
          | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Верхнє меню. Порядок змінюється перетягуванням.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        /**
         * Сторінка сайту: /diyalnist. Зовнішній сайт: https://… Порожньо — пункт лише відкриває підменю.
         */
        url?: string | null;
        children?:
          | {
              label: string;
              /**
               * Сторінка сайту: /diyalnist. Зовнішній сайт: https://… Порожньо — пункт лише відкриває підменю.
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Загальну кількість дзвінків рахувати не треба — сайт сам додає всі категорії.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  asOf?: string | null;
  show?: boolean | null;
  title?: string | null;
  subtitle?: string | null;
  /**
   * На сайті сортуються автоматично — від більшої до меншої.
   */
  categories?:
    | {
        name: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  registered?: number | null;
  messengers?: number | null;
  note?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Загальну кількість, вхідні та вихідні дзвінки рахувати не треба — сайт сам додає відповідні рядки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-report".
 */
export interface AnnualReport {
  id: number;
  show?: boolean | null;
  periodFrom?: string | null;
  periodTo?: string | null;
  title?: string | null;
  subtitle?: string | null;
  /**
   * Сума цих рядків = «Вхідні дзвінки». Кольори йдуть по черзі: синій, блакитний, жовтий, сірий. Не більше 4 рядків.
   */
  channels?:
    | {
        name: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  line1648?: number | null;
  sms?: number | null;
  /**
   * Показуються в тому порядку, як тут — від найчастішого.
   */
  topQuestions?:
    | {
        name: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Сума цих рядків = «Вихідні дзвінки».
   */
  outgoing?:
    | {
        name: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Кількість населених пунктів (НП) у підсумках сайт рахує сам — додаючи числа всіх областей. Вручну вводяться лише кількості громад (ТГ).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territories".
 */
export interface Territory {
  id: number;
  show?: boolean | null;
  title?: string | null;
  subtitle?: string | null;
  communities?: {
    possible?: number | null;
    eres?: number | null;
    active?: number | null;
    occupied?: number | null;
  };
  /**
   * Кількість населених пунктів за статусами. Кружечок з’являється на мапі для кожної області зі списку.
   */
  regions?:
    | {
        region:
          | 'UA-43'
          | 'UA-05'
          | 'UA-07'
          | 'UA-12'
          | 'UA-14'
          | 'UA-18'
          | 'UA-21'
          | 'UA-23'
          | 'UA-26'
          | 'UA-32'
          | 'UA-35'
          | 'UA-09'
          | 'UA-46'
          | 'UA-48'
          | 'UA-51'
          | 'UA-53'
          | 'UA-56'
          | 'UA-59'
          | 'UA-61'
          | 'UA-63'
          | 'UA-65'
          | 'UA-68'
          | 'UA-71'
          | 'UA-77'
          | 'UA-74';
        possible?: number | null;
        eres?: number | null;
        active?: number | null;
        occupied?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр.: «…затверджений наказом Мінрозвитку від 28.02.2025 № 376 (зі змінами…)»
   */
  source?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  /**
   * PNG із прозорим фоном, квадратний. Якщо не вибрано — використовується стандартна емблема.
   */
  logo?: (number | null) | Media;
  kicker?: string | null;
  orgName?: string | null;
  shortName?: string | null;
  address?: string | null;
  schedule?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  phones?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  hotline?: {
    number?: string | null;
    lines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        text?: T;
        primary?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              url?: T;
            };
        flagMode?: T;
        flagVideo?: T;
        videoSpeed?: T;
        flagSpeed?: T;
      };
  statement?:
    | T
    | {
        title?: T;
        text?: T;
      };
  cards?:
    | T
    | {
        color?: T;
        size?: T;
        live?: T;
        icon?: T;
        label?: T;
        number?: T;
        title?: T;
        text?: T;
        chips?:
          | T
          | {
              text?: T;
              id?: T;
            };
        linkLabel?: T;
        url?: T;
        id?: T;
      };
  evacuation?:
    | T
    | {
        show?: T;
        highlight?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        footer?: T;
        footerHighlight?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  asOf?: T;
  show?: T;
  title?: T;
  subtitle?: T;
  categories?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  registered?: T;
  messengers?: T;
  note?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-report_select".
 */
export interface AnnualReportSelect<T extends boolean = true> {
  show?: T;
  periodFrom?: T;
  periodTo?: T;
  title?: T;
  subtitle?: T;
  channels?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  line1648?: T;
  sms?: T;
  topQuestions?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  outgoing?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territories_select".
 */
export interface TerritoriesSelect<T extends boolean = true> {
  show?: T;
  title?: T;
  subtitle?: T;
  communities?:
    | T
    | {
        possible?: T;
        eres?: T;
        active?: T;
        occupied?: T;
      };
  regions?:
    | T
    | {
        region?: T;
        possible?: T;
        eres?: T;
        active?: T;
        occupied?: T;
        id?: T;
      };
  source?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  logo?: T;
  kicker?: T;
  orgName?: T;
  shortName?: T;
  address?: T;
  schedule?:
    | T
    | {
        text?: T;
        id?: T;
      };
  email?: T;
  phones?:
    | T
    | {
        text?: T;
        id?: T;
      };
  hotline?:
    | T
    | {
        number?: T;
        lines?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'news';
      value: number | News;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  items?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  items?:
    | {
        icon?:
          | (
              | 'heart'
              | 'scales'
              | 'phone'
              | 'home'
              | 'building'
              | 'search'
              | 'document'
              | 'map'
              | 'info'
              | 'warning'
              | 'globe'
            )
          | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatBlock".
 */
export interface StatBlock {
  /**
   * Напр.: 2 150 010+
   */
  number: string;
  label: string;
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stat';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}